import Head from "next/head";
import Image from "next/image";
import Typewriter from "typewriter-effect/dist/core";
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import Projets from "../components/Projets";
import styles from "../styles/Home.module.css";
import { Animated } from "react-animated-css";
import Zoom from "react-reveal/Zoom";
import Fade from "react-reveal/Fade";
import Reveal from "react-reveal/Reveal";
import { Navbar } from "../components/Navbar";
import { useEffect, useState } from "react";
import "animate.css";
import config from "react-reveal/globals";

export default function Home() {
  config({ ssrFadeout: true });

  const [isDarkMode, setIsDarkMode] = useState(false);
  <Typewriter
    onInit={(typewriter) => {
      typewriter
        .typeString("Hello World!")
        .callFunction(() => {
          console.log("String typed out!");
        })
        .pauseFor(2500)
        .deleteAll()
        .callFunction(() => {
          console.log("All strings were deleted");
        })
        .start();
    }}
  />;
  // useEffect(() => {
  //   AOS.init();
  //   AOS.refresh();
  // }, []);
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"
        />{" "}
      </Head>
      <main className={styles.main}>
        {/* <Navbar /> */}
        <section className={styles.container}>
          <div className={styles.contentLeft}>
            <Animated animationIn="fadeInUp" isVisible={true}>
              <h1 className={styles.title}>Oussama Dabachil</h1>
              <h2 className={styles.subtitle}>
                Développeur FullStack Javascript
              </h2>
            </Animated>

            <ul>
              <li>Mes formations</li>
              <li>Mes compétences</li>
              <li>Mes projets</li>
              <li>Me contacter</li>
            </ul>
          </div>
          <div className={styles.contentRight}>
            <Animated animationIn="fadeInRight" isVisible={true}>
              <img
                className={styles.image}
                src="/oussama2.jpeg"
                alt="React Image"
              />
            </Animated>
          </div>
        </section>
        <section className={styles.containertwo}>
          <Zoom>
            <figure>
              <img
                className={styles.imageHome}
                src="/oussama2.jpeg"
                alt="React Image"
              />{" "}
              <figcaption>
                <p>
                  Bonjour , je m’appelle Oussama Dabachil et je suis un
                  développeur passionné par le monde du développement .
                </p>
              </figcaption>
            </figure>
          </Zoom>

          <h3 className={styles.titleAccueil}>Mes formations</h3>

          <hr className={styles.horizontal}></hr>

          <div className={styles.containerFormation}>
            <Reveal effect="fadeInUp">
              <div className={styles.blockLeft}>
                <h4>
                  <span>Lieu</span>
                  <span>
                    {" "}
                    : La Capsule , 56 Boulevard Pereire , Levallois Perret
                  </span>
                </h4>
                <h4>
                  <span>Du </span>
                  <span> : 11/10/2022 </span>
                </h4>
                <h4>
                  <span>Jusqu’au </span>
                  <span>: 23/12/2022</span>
                </h4>
                <h4>
                  <span>Durée </span>
                  <span>: 10 semaines</span>
                </h4>
              </div>
            </Reveal>
            <Reveal effect="fadeInUp">
              <div className={styles.blockRight}>
                <h4>
                  <span>Nom de la formation</span>
                  <span> Titre RNCP 6 développeur web et web mobile</span>
                </h4>
                <h4>
                  <span>Résumé de la formation :</span>
                  <span>
                    Coding Bootcamp de 10 semaines - Développeur web et mobile
                    Fullstack JavaScript
                    <ul>
                      <li>
                        Conception et prototypage d’applications web et mobile
                      </li>
                      <li>
                        Programmation Front-end : HTML 5 / CSS / JavaScript /
                        React / Redux
                      </li>
                      <li>Programmation Back-end : Node.JS / Express</li>
                      <li>Base de données et CDN: Mongo DB / Cloudinary </li>
                      <li>Workflow : Git / Github </li>
                    </ul>
                  </span>
                </h4>
              </div>
            </Reveal>
          </div>
          <hr className={styles.horizontal}></hr>

          <div className={styles.containerFormation}>
            <Reveal effect="fadeInUp">
              <div className={styles.blockLeft}>
                <h4>
                  <span>Lieu</span>
                  <span>
                    {" "}
                    : ITIC Paris ,190bis Boulevard de Charonne, 75020 Paris
                  </span>
                </h4>
                <h4>
                  <span>Du </span>
                  <span> : 01/09/2020 </span>
                </h4>
                <h4>
                  <span>Jusqu’au </span>
                  <span>: 23/06/2022</span>
                </h4>
                <h4>
                  <span>Durée </span>
                  <span>: 2 années </span>
                </h4>
              </div>
            </Reveal>
            <Reveal effect="fadeInUp">
              <div className={styles.blockRight}>
                <h4>
                  <span>Nom de la formation</span>
                  <span> BTS SIO option SLAM</span>
                </h4>
                <h4>
                  <span>Résumé de la formation :</span>
                  <span>
                    <ul>
                      <li>
                        Apprentissage de langages Frontend tel que HTML CSS et
                        Javascript
                      </li>
                      <li>
                        Apprentissage de langages Backend tel que Java et PHP
                      </li>
                      <li>Apprentissage de SQL , Base de données</li>
                      <li>
                        Réalisation de sites dynamiques pour le projet de fin
                        d’années (HTML , CSS, Javascript et PHP){" "}
                      </li>
                      <li>Workflow : Git / Github </li>
                    </ul>
                  </span>
                </h4>
              </div>
            </Reveal>
          </div>
          <hr className={styles.horizontal}></hr>

          <div className={styles.containerFormation}>
            <Reveal effect="fadeInUp">
              <div className={styles.blockLeft}>
                <h4>
                  <span>Lieu</span>
                  <span>
                    {" "}
                    :IUT Cachan , 9 Av. de la Division Leclerc, 94230 Cachan
                  </span>
                </h4>
                <h4>
                  <span>Du </span>
                  <span> : 01/09/2019 </span>
                </h4>
                <h4>
                  <span>Jusqu’au </span>
                  <span>: 01/09/2020</span>
                </h4>
                <h4>
                  <span>Durée </span>
                  <span>: 1 année </span>
                </h4>
              </div>
            </Reveal>
            <Reveal effect="fadeInUp">
              <div className={styles.blockRight}>
                <h4>
                  <span>Nom de la formation</span>
                  <span>
                    {" "}
                    DUT Génie électrique et informatique industrielle (1 an){" "}
                  </span>
                </h4>
                <h4>
                  <span>Résumé de la formation :</span>
                  <span>
                    <ul>
                      <li>
                        Apprentissage de langages Frontend tel que HTML CSS et
                        Javascript
                      </li>
                      <li>Apprentissage de langages tel que le C et Python</li>
                      <li>
                        Apprentissage de logiciels tel que Kicad pour la
                        modélisation des cartes électroniques .
                      </li>
                      <li>Projet Robot suiveur de ligne</li>
                    </ul>
                  </span>
                </h4>
              </div>
            </Reveal>
          </div>
          <h3 className={styles.titleAccueil}>Mes compétences</h3>
          <section className={styles.containerthree}>
            <div className={styles.containerCompetence}>
              <Reveal effect="fadeInLeft">
                <div className={styles.blockLeftSkills}>
                  <h4 className={styles.titleTypeSkills}>Frontend</h4>
                </div>
              </Reveal>
              <Reveal effect="fadeInRight">
                <div className={styles.blockRightSkills}>
                  <ul>
                    <li>
                      HTML
                      <span>
                        <hr className={styles.animatedHr}></hr>
                      </span>
                    </li>
                    <li>
                      CSS
                      <span>
                        <hr className={styles.animatedHr}></hr>
                      </span>
                    </li>
                    <li>
                      JavaScript
                      <span>
                        <hr className={styles.animatedHr}></hr>
                      </span>
                    </li>
                    <li>
                      React JS
                      <span>
                        <hr className={styles.animatedHr}></hr>
                      </span>
                    </li>
                    <li>
                      React Native
                      <span>
                        <hr className={styles.animatedHr}></hr>
                      </span>
                    </li>
                    <li>
                      Redux
                      <span>
                        <hr className={styles.animatedHr}></hr>
                      </span>
                    </li>
                    <li>
                      Bootstrap
                      <span>
                        <hr className={styles.animatedHr}></hr>
                      </span>
                    </li>
                    <li>
                      Material UI
                      <span>
                        <hr className={styles.animatedHr}></hr>
                      </span>
                    </li>
                    <li>
                      Tailwind CSS
                      <span>
                        <hr className={styles.animatedHr}></hr>
                      </span>
                    </li>
                  </ul>
                </div>
              </Reveal>
            </div>
            <div className={styles.containerCompetence}>
              <Reveal effect="fadeInLeft">
                <div className={styles.blockLeftSkillsBackend}>
                  <h4 className={styles.titleTypeSkills}>Backend</h4>
                </div>
              </Reveal>
              <Reveal effect="fadeInRight">
                <div className={styles.blockRightSkillsBackend}>
                  <ul>
                    <li>
                      Express JS
                      <span>
                        <hr className={styles.animatedHr}></hr>
                      </span>
                    </li>
                    <li>
                      Java
                      <span>
                        <hr className={styles.animatedHr}></hr>
                      </span>
                    </li>
                    <li>
                      Node JS
                      <span>
                        <hr className={styles.animatedHr}></hr>
                      </span>
                    </li>
                    <li>
                      PHP
                      <span>
                        <hr className={styles.animatedHr}></hr>
                      </span>
                    </li>
                    <li>
                      Symphony
                      <span>
                        <hr className={styles.animatedHr}></hr>
                      </span>
                    </li>
                  </ul>
                </div>
              </Reveal>
            </div>
          </section>
          <div className={styles.containerProjets}>
           
            <h3 className={styles.titleAccueil2}>Mes projets</h3>
            <div className={styles.mesProjetsContainer}>
              <div className={styles.mesProjetsContainer}>
                <Projets/>
    
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer></footer>
    </>
  );
}
